language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test --verbose
  - cargo build --features pylib
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "Working on master branch" && cargo package --verbose; fi
